ExpenseTracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
]

tracker/urls.py
from django.urls import path
from tracker.views import auth_views
from tracker.views import landing_views
from tracker.views import customer_views
from tracker.views import project_views
from tracker.views import expense_views


app_name = 'tracker'
urlpatterns = [
    # auth
    path('login/', auth_views.login_view, name='login'),
    path('logout', auth_views.logout_view, name='logout'),

    # landing
    path('', landing_views.index, name='index'),

    # customer
    path('customer', customer_views.index, name='customer'),
    path('customer/create', customer_views.create, name='customer_create'),
    path('customer/store', customer_views.store, name='customer_store'),
    path('customer/<int:id>', customer_views.edit, name='customer_edit'),
    path('customer/<int:id>/update', customer_views.update, name='customer_update'),
    path('customer/<int:id>/delete', customer_views.delete, name='customer_delete'),

    # project
    path('project', project_views.index, name='project'),
    path('project/create', project_views.create, name='project_create'),
    path('project/store', project_views.store, name='project_store'),
    path('project/<int:id>', project_views.edit, name='project_edit'),
    path('project/<int:id>/update', project_views.update, name='project_update'),
    path('project/<int:id>/delete', project_views.delete, name='project_delete'),

    # expense
    path('project/<int:project_id>/expense', expense_views.index, name='expense'),
    path('project/<int:project_id>/expense/create', expense_views.create, name='expense_create'),
    path('project/<int:project_id>/expense/store', expense_views.store, name='expense_store'),
    path('expense/<int:expense_id>', expense_views.edit, name='expense_edit'),
    path('expense/<int:expense_id>/update', expense_views.update, name='expense_update'),
    path('expense/<int:expense_id>/delete', expense_views.delete, name='expense_delete'),

]

tracker/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField('name', max_length=100)
    address = models.CharField('address', max_length=100)
    contact_number = models.CharField('contact_number', max_length=100)

    class Meta:
        db_table = "customer"


class Category(models.Model):
    name = models.CharField('name', max_length=255)

    class Meta:
        db_table = "category"


class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    title = models.CharField('title', max_length=100)
    description = models.TextField('description')
    customer_order_no = models.IntegerField('customer_order_no', default=0)
    status = models.CharField('status', max_length=30)
    value = models.FloatField('value', default=0)
    created_at = models.DateTimeField(default=datetime.datetime.now)
    updated_at = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        db_table = "project"


class Expense(models.Model):
    project = models.ForeignKey('Project', on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    date = models.DateField("date", default=datetime.date.today)
    receipt_no = models.IntegerField('receipt_no', default=0)
    description = models.TextField('description')
    vat = models.FloatField('vat', default=0)
    total_amount = models.FloatField('total_amount', default=0)

    class Meta:
        db_table = "expense"

tracker/views/auth_views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


def login_view(request, next='/'):
    if 'next' in request.GET:
        next = request.GET['next']
    if request.method == 'POST':
        next = request.POST.get('next')
        username = request.POST.get('username')
        password = request.POST.get('password')
        if username == "" or password == "":
            messages.warning(request, 'your login data are incorrect.')
            return redirect(next)
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
        else:
            messages.warning(request, 'your login data are incorrect.')
        return redirect(next)
    if request.user.is_authenticated:
        return redirect('/')
    return render(request, 'login.html', {'next': next})


def logout_view(request):
    messages.success(request, 'successfully logout.')
    logout(request)

    response = HttpResponseRedirect('/')
    return response

tracker/views/customer_views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from tracker.models import Customer


@login_required
def index(request):
    user_id = request.user.id
    customers = Customer.objects.filter(user_id=user_id)
    return render(request, 'customer/index.html', {'customers': customers})


@login_required
def create(request):
    return render(request, 'customer/create.html')


def store(request):
    user_id = request.user.id
    name = request.POST.get('name')
    address = request.POST.get('address')
    contact_number = request.POST.get('contact_number')
    customer = Customer()
    customer.user_id = user_id
    customer.name = name
    customer.address = address
    customer.contact_number = contact_number
    customer.save()
    return redirect('tracker:customer')


def edit(request, id):
    customer = Customer.objects.get(id=id)
    return render(request, 'customer/edit.html', {'customer': customer})


def update(request, id):
    name = request.POST.get('name')
    address = request.POST.get('address')
    contact_number = request.POST.get('contact_number')
    Customer.objects.filter(id=id).update(name=name,
                                          address=address,
                                          contact_number=contact_number)
    return redirect('tracker:customer')


def delete(request, id):
    Customer.objects.filter(id=id).delete()
    return redirect('tracker:customer')

tracker/views/expense_views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from tracker.models import Project, Expense, Category, Customer


@login_required
def index(request, project_id):
    expenses = Expense.objects.filter(project_id=project_id)
    return render(request, 'expense/index.html', {'expenses': expenses, 'project_id': project_id})


@login_required
def create(request, project_id):
    categories = Category.objects.all()
    return render(request, 'expense/create.html', {'categories': categories, 'project_id': project_id})


def store(request, project_id):
    date = request.POST.get('date')
    receipt_no = request.POST.get('receipt_no')
    vat = request.POST.get('vat')
    total_amount = request.POST.get('total_amount')
    category = request.POST.get('category')
    expense = Expense()
    expense.project_id = project_id
    expense.date = date
    expense.receipt_no = int(receipt_no)
    expense.vat = float(vat)
    expense.total_amount = float(total_amount)
    expense.category_id = category
    expense.save()
    return redirect('tracker:expense', project_id=project_id)


def edit(request, expense_id):
    categories = Category.objects.all()
    expense = Expense.objects.get(id=expense_id)
    project_id = expense.project_id
    return render(request, 'expense/edit.html', {'expense': expense,
                                                 'project_id': project_id,
                                                 'categories': categories})


def update(request, expense_id):
    date = request.POST.get('date')
    receipt_no = request.POST.get('receipt_no')
    vat = request.POST.get('vat')
    total_amount = request.POST.get('total_amount')
    category = request.POST.get('category')
    project_id = Expense.objects.get(id=expense_id).project_id
    Expense.objects.filter(id=expense_id).update(
                                         date=date,
                                         receipt_no=receipt_no,
                                         vat=vat,
                                         total_amount=total_amount,
                                         category=category
                                         )
    return redirect('tracker:expense', project_id=project_id)


def delete(request, expense_id):
    project_id = Expense.objects.get(id=expense_id).project_id
    Expense.objects.filter(id=expense_id).delete()
    return redirect('tracker:expense', project_id=project_id)

tracker/views/landing_views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from tracker.models import Project


@login_required
def index(request):
    user_id = request.user.id
    projects = Project.objects.filter(user_id=user_id).order_by('-created_at')[:5]
    return render(request, 'landing_page.html', {'projects': projects, 'user_id': user_id})

tracker/views/project_views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from tracker.models import Project, Expense, Category, Customer


@login_required
def index(request):
    user_id = request.user.id
    projects = Project.objects.filter(user_id=user_id)
    return render(request, 'project/index.html', {'projects': projects})


@login_required
def create(request):
    categories = Category.objects.all()
    user_id = request.user.id
    customers = Customer.objects.filter(user_id=user_id)
    return render(request, 'project/create.html', {'categories': categories, 'customers': customers})


def store(request):
    # project
    user_id = request.user.id
    title = request.POST.get('title')
    description = request.POST.get('description')
    customer_id = request.POST.get('customer_id')
    customer_order_no = request.POST.get('customer_order_no')
    status = request.POST.get('status')
    amount = request.POST.get('amount')
    project = Project()
    project.user_id = user_id
    project.customer_id = customer_id
    project.title = title
    project.description = description
    project.customer_order_no = customer_order_no
    project.status = status
    project.value = float(amount)
    project.save()
    return redirect('tracker:project')


def edit(request, id):
    categories = Category.objects.all()
    project = Project.objects.get(id=id)
    user_id = request.user.id
    customers = Customer.objects.filter(user_id=user_id)
    return render(request, 'project/edit.html', {'project': project,
                                                 'customers': customers,
                                                 'categories': categories})


def update(request, id):
    title = request.POST.get('title')
    description = request.POST.get('description')
    customer_id = request.POST.get('customer_id')
    customer_order_no = request.POST.get('customer_order_no')
    status = request.POST.get('status')
    amount = request.POST.get('amount')

    Project.objects.filter(id=id).update(title=title,
                                         description=description,
                                         customer_id=customer_id,
                                         customer_order_no=customer_order_no,
                                         status=status,
                                         value=amount
                                         )

    return redirect('tracker:project')


def delete(request, id):
    Project.objects.filter(id=id).delete()
    return redirect('tracker:project')

tracker/templates/customer/_form.html
<div class="portlet">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-user"></i>Customer
        </div>
        <div class="actions btn-set">
            <a href="{% url 'tracker:customer' %}" name="back" class="btn btn-secondary-outline">
                <i class="fa fa-angle-left"></i> Back</a>
            <button class="btn btn-success">
                <i class="fa fa-check"></i> Save
            </button>
        </div>
    </div>
    <div class="portlet-body">
        <div class="tabbable-bordered">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#tab_general" data-toggle="tab"> General </a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab_general">
                    <div class="form-body">
                        <div class="form-group">
                            <label class="col-md-2 control-label">Name:
                                <span class="required"> * </span>
                            </label>
                            <div class="col-md-3">
                                <input type="text" class="form-control" name="name" value="{{ customer.name }}" placeholder="" required></div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">Address:
                                <span class="required"> * </span>
                            </label>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="address" value="{{ customer.address }}" placeholder="" required></div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">Contact Number:
                                <span class="required"> * </span>
                            </label>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="contact_number" value="{{ customer.contact_number }}" placeholder="" required></div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

tracker/templates/customer/create.html
{% extends "layouts/main_template.html" %}
{% block css %}
    {% load static %}
    <link href="{% static 'assets/global/plugins/datatables/datatables.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<body class="page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo">
    <!-- BEGIN HEADER -->
    {% include 'partials/header.html' %}
    <!-- END HEADER -->
    <!-- BEGIN CONTAINER -->
    <div class="page-container">
        <!-- BEGIN SIDEBAR -->
        {% include 'partials/navbar.html' %}
        <!-- END SIDEBAR -->
        <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <!-- BEGIN CONTENT BODY -->
            <div class="page-content">
                <!-- BEGIN PAGE HEAD-->
                <div class="page-head">
                    <!-- BEGIN PAGE TITLE -->
                    <div class="page-title">
                        <h1>Create Customer
                        </h1>
                    </div>
                    <!-- END PAGE TITLE -->
                </div>
                <!-- END PAGE HEAD-->
                <!-- BEGIN PAGE BREADCRUMB -->
                <ul class="page-breadcrumb breadcrumb">
                    <li>
                        <a href="/">Home</a>
                        <i class="fa fa-circle"></i>
                    </li>
                    <li>
                        <span class="active">Customers</span>
                    </li>
                </ul>
                <!-- END PAGE BREADCRUMB -->
                <!-- BEGIN PAGE BASE CONTENT -->
                <div class="row">
                    <div class="col-md-12">
                        <form class="form-horizontal form-row-seperated" action="{% url 'tracker:customer_store' %}" method="post">
                        {% csrf_token %}
                        {% include 'customer/_form.html' %}
                        </form>
                    </div>
                </div>
                <!-- END PAGE BASE CONTENT -->
            </div>
            <!-- END CONTENT BODY -->
        </div>
        <!-- END CONTENT -->
    </div>
    <!-- END CONTAINER -->

{% endblock %}

{% block js %}
<script src="{% static 'assets/global/scripts/datatable.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/datatables/datatables.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/pages/scripts/table-datatables-managed.min.js' %}" type="text/javascript"></script>

{% endblock %}

tracker/templates/customer/edit.html
{% extends "layouts/main_template.html" %}
{% block css %}
    {% load static %}
    <link href="{% static 'assets/global/plugins/datatables/datatables.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<body class="page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo">
    <!-- BEGIN HEADER -->
    {% include 'partials/header.html' %}
    <!-- END HEADER -->
    <!-- BEGIN CONTAINER -->
    <div class="page-container">
        <!-- BEGIN SIDEBAR -->
        {% include 'partials/navbar.html' %}
        <!-- END SIDEBAR -->
        <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <!-- BEGIN CONTENT BODY -->
            <div class="page-content">
                <!-- BEGIN PAGE HEAD-->
                <div class="page-head">
                    <!-- BEGIN PAGE TITLE -->
                    <div class="page-title">
                        <h1>Edit Customer
                        </h1>
                    </div>
                    <!-- END PAGE TITLE -->
                </div>
                <!-- END PAGE HEAD-->
                <!-- BEGIN PAGE BREADCRUMB -->
                <ul class="page-breadcrumb breadcrumb">
                    <li>
                        <a href="/">Home</a>
                        <i class="fa fa-circle"></i>
                    </li>
                    <li>
                        <span class="active">Customers</span>
                    </li>
                </ul>
                <!-- END PAGE BREADCRUMB -->
                <!-- BEGIN PAGE BASE CONTENT -->
                <div class="row">
                    <div class="col-md-12">
                        <form class="form-horizontal form-row-seperated" action="{% url 'tracker:customer_update' customer.id%}" method="post">
                        {% csrf_token %}
                        {% include 'customer/_form.html' %}
                        </form>
                    </div>
                </div>
                <!-- END PAGE BASE CONTENT -->
            </div>
            <!-- END CONTENT BODY -->
        </div>
        <!-- END CONTENT -->
    </div>
    <!-- END CONTAINER -->

{% endblock %}

{% block js %}
<script src="{% static 'assets/global/scripts/datatable.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/datatables/datatables.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/pages/scripts/table-datatables-managed.min.js' %}" type="text/javascript"></script>

{% endblock %}

tracker/templates/customer/index.html
{% extends "layouts/main_template.html" %}
{% block css %}
    {% load static %}
    <link href="{% static 'assets/global/plugins/datatables/datatables.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
<body class="page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo">
    <!-- BEGIN HEADER -->
    {% include 'partials/header.html' %}
    <!-- END HEADER -->
    <!-- BEGIN CONTAINER -->
    <div class="page-container">
        <!-- BEGIN SIDEBAR -->
        {% include 'partials/navbar.html' %}
        <!-- END SIDEBAR -->
        <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <!-- BEGIN CONTENT BODY -->
            <div class="page-content">
                <!-- BEGIN PAGE HEAD-->
                <div class="page-head">
                    <!-- BEGIN PAGE TITLE -->
                    <div class="page-title">
                        <h1>Manage Customers
                        </h1>
                    </div>
                    <!-- END PAGE TITLE -->
                </div>
                <!-- END PAGE HEAD-->
                <!-- BEGIN PAGE BREADCRUMB -->
                <ul class="page-breadcrumb breadcrumb">
                    <li>
                        <a href="/">Home</a>
                        <i class="fa fa-circle"></i>
                    </li>
                    <li>
                        <span class="active">Customers</span>
                    </li>
                </ul>
                <!-- END PAGE BREADCRUMB -->
                <!-- BEGIN PAGE BASE CONTENT -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="portlet light bordered">
                            <div class="portlet-body">
                                <div class="table-toolbar">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="btn-group">
                                                <a href="{% url 'tracker:customer_create' %}" class="btn sbold green"> Add New
                                                    <i class="fa fa-plus"></i>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <table class="table table-striped table-bordered table-hover order-column" id="sample_1">
                                    <thead>
                                        <tr>
                                            <th width="20%"> Name </th>
                                            <th width="30%"> Address </th>
                                            <th width="20%"> Contact Number </th>
                                            <th width="30%"> Actions </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for customer in customers %}
                                        <tr class="odd gradeX">
                                            <td>{{ customer.name }}</td>
                                            <td>{{ customer.address }}</td>
                                            <td>{{ customer.contact_number }}</td>
                                            <td class="center">
                                                <a href="{% url 'tracker:customer_edit' customer.id%}" class="btn btn-xs default btn-editable"><i class="fa fa-pencil"></i> EDIT</a>
                                                <a href="{% url 'tracker:customer_delete' customer.id%}" class="btn btn-xs default btn-editable"><i class="fa fa-trash"></i> DELETE</a>
                                            </td>

                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- END PAGE BASE CONTENT -->
            </div>
            <!-- END CONTENT BODY -->
        </div>
        <!-- END CONTENT -->
    </div>
    <!-- END CONTAINER -->

{% endblock %}

{% block js %}
<script src="{% static 'assets/global/scripts/datatable.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/datatables/datatables.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/pages/scripts/table-datatables-managed.min.js' %}" type="text/javascript"></script>

{% endblock %}